### ISSUE TITLE
Would be helpful to include vendor and/or product family on the dashboard to allow quick scan

### ISSUE THREAD

**Issue by alberg214** [KwnyPwny/cvecrowd.com#2]
This would help avoid extra clicks for users

Something like "Citrix/Netscaler" or "Cisco/IOS" 

Thanks for building this!

**Comment by KwnyPwny** [comment]
This is now implemented although I am not happy with the capitalization yet.

**Comment by alberg214** [comment]
Wow!  Quick response - thanks - this is really helpful.
Have a great weekend
Al
