### ISSUE TITLE
Additional data - EPSS score

### ISSUE THREAD

**Issue by alberg214** [KwnyPwny/cvecrowd.com#5]
Another piece of data that would be interesting - the EPSS score for each vulnerability

**Comment by KwnyPwny** [comment]
I wasn't familiar with EPSS score. I'm not entirely convinced that this is a useful metric but if it helps you, I am not against implementing it :)

As this requires me to query another API (https://www.first.org/epss/data_stats), implementing this will take a little longer.

**Comment by jayjacobs** [comment]
Happy to offer whatever help I can on the EPSS side (I am a lead on the project), there is also a single http call to get all of the "current" EPSS scores in one call, that may be easier to just run once a day: https://epss.cyentia.com/epss_scores-current.csv.gz (link is off of https://www.first.org/epss/data_stats).

**Comment by KwnyPwny** [comment]
Implemented EPSS :)

**Comment by alberg214** [comment]
Great news!
Thanks for letting me know
Al

 Al Berg / ***@***.*** / www.paranoidprose.com
