### ISSUE TITLE
Additional data - make the CVE number clickable into the NVD

### ISSUE THREAD

**Issue by alberg214** [KwnyPwny/cvecrowd.com#6]
Would make this even more useful.  This is what you get for implementing my first change request so quickly.  No good deed goes unpunished :-)

**Comment by KwnyPwny** [comment]
There's a link to NVD already in the CVE info field. Isn't that sufficient?
![image](https://github.com/KwnyPwny/cvecrowd.com/assets/7549545/11ecb94f-c6e5-4b87-b7e9-4bb4064a4827)

**Comment by alberg214** [comment]
Thanks - I didn’t notice that initially.
