### ISSUE TITLE
Question on Instance Coverage

### ISSUE THREAD

**Issue by captn3m0** [KwnyPwny/cvecrowd.com#8]
Just curious how this searches across instances? If I post about a CVE on a brand new instance, what will it take to show up here?

**Comment by KwnyPwny** [comment]
I'm using the search API from the Mastodon instance https://infosec.exchange. Every Mastodon instance federating with it, should eventually show up on cvecrowd.

**Comment by captn3m0** [comment]
Just to confirm:

1. My post should be public
2. My account should be followed by someone at infosec.exchange.
3. The "search indexing" opt-in is not relevant here at all.
4. It doesn't matter what version of Mastodon, or what server itself I use, as long as I can be followed by an account at infosec.exchange

> This website lists CVEs that are currently being discussed on the social network [Mastodon](https://joinmastodon.org/).

Maybe this should be changed to Mastodon/Fediverse in that case? You can have posts by users outside of Mastodon that will show up on CVECrowd.

**Comment by KwnyPwny** [comment]
> Maybe this should be changed to Mastodon/Fediverse in that case? You can have posts by users outside of Mastodon that will show up on CVECrowd.

Yes, I recognized that inaccuracy yesterday as well. I guess the most precise definition is:

**This website lists CVEs that are currently being discussed on social networks federating with infosec.exchange.**

Such social networks must support *ActivityPub* as it is the backbone of the Fediverse / Mastodon.


> 1. My post should be public
> 2. My account should be followed by someone at infosec.exchange.

Yes to both.

> 3. The "search indexing" opt-in is not relevant here at all.

This is wrong: I am not parsing the federated timeline of infosec.exchange. I only use the search API (fulltext and hashtags).

> 4. It doesn't matter what version of Mastodon, or what server itself I use, as long as I can be followed by an account at infosec.exchange

I am not sure about that. infosec.exchange is on Mastodon 4.2, which had major updates to the search function. I do not know whether the search requires other instances to also use at least 4.2.

**Comment by KwnyPwny** [comment]
I've just updated CVE Crowd and published a blog post that explains under which conditions posts are listed: https://kpwn.de/2023/12/cve-crowd-conditions-for-posts-to-be-listed/
